version: '3.3'
services:
    mariadb:
        image: mariadb
        restart: always
        ports:
        - 3308:3306
        environment:
            MYSQL_DATABASE: gtd
            MYSQL_ROOT_PASSWORD: UVccgtumSpFpEi76zs1Ww8UZFNrDF8u1CGYbtWmXdm7M4NjLqufdLxf5pTP7FFRTfW3akV9QXeI8YQse4aeHDrArWiPFq81Mh7v6q1mCsUFMq9FYkboDgLFp34xK3Adt
            MYSQL_USER: AUTOMAT
            MYSQL_PASSWORD: WiTSDmtChVmNS53szQZTh5mwPFHTAc9k
        volumes:
            - ./Mariadb:/docker-entrypoint-initdb.d
            - ./DB:/var/lib/mysql
    api:
        build: ./api
        restart: always
        volumes: 
            - ./api/:/app
        ports:
            - 8000:80
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./Nginx/core:/etc/nginx/conf.d
            - ./Nginx/www:/var/www/
            - ./Nginx/Logs:/var/log/nginx/
            - ./Nginx/html:/usr/share/nginx/html/
